name: 更新并替换 TV.json

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tv-json:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v3
      with:
        ref:${{ github.ref }}

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 运行 Python 脚本生成 TV.json
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_BRANCH: ${{ github.ref_name }}
      run: |
        python merge_sites.py

    - name: 检查 TV.json 是否生成
      id: check_tv_json
      run: |
        if [ -f "TV.json" ]; then
          echo "::set-output name=tv_json_exists::true"
        else
          echo "TV.json 未生成。"
          echo "::set-output name=tv_json_exists::false"
          exit 1
        fi

    - name: 配置 Git
      if: steps.check_tv_json.outputs.tv_json_exists == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: 提交并强制推送 TV.json
      if: steps.check_tv_json.outputs.tv_json_exists == 'true'
      run: |
        git add TV.json
        git commit -m "自动更新 TV.json [skip ci]"
        git push origin ${{ github.ref }} --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
